name: farmrecord
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0  # Updated
  firebase_auth: ^5.2.0
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.4.0
  intl: ^0.20.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 

flutter:
  uses-material-design: true

  assets:
    - assets/background.jpg
    - assets/images/farming.jpg
    - assets/image1.jpg
    # - assets/image2.jpg
    # - assets/image3.jpg
